name: Network OTBR
version: "5.0.0"
slug: network_otbr
description: OpenThread Border Router for a network-connected RCP
url: https://github.com/bachjessen/homeassistant-network-otbr-app
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
host_network: true
host_uts: true
privileged:
  - NET_ADMIN
  - IPC_LOCK
devices:
  - /dev/net/tun
options:
  network_device: 10.40.10.11:6638
  backbone_interface: end0
  baudrate: "460800"
  flow_control: false
  otbr_log_level: notice
  firewall: true
  nat64: false
  beta: false
schema:
  network_device: str
  backbone_interface: str
  baudrate: list(57600|115200|230400|460800|921600|1000000)
  flow_control: bool
  otbr_log_level: list(debug|info|notice|warning|error|critical|alert|emergency)
  firewall: bool
  nat64: bool
  beta: bool
ports:
  8080/tcp: null
  8081/tcp: null
ports_description:
  8080/tcp: OpenThread Web interface
  8081/tcp: OpenThread REST API
